version: "3.9"

services:
  main:
    build:
      context: .
      dockerfile: main/Dockerfile
    image: backend_update-main
    container_name: main
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "20721:20721"
    restart: unless-stopped

  embedding_compute:
    build:
      context: .
      dockerfile: embedding_compute/Dockerfile
    image: backend_update-embedding_compute
    container_name: embedding_compute
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "20722:20722"
    restart: unless-stopped

  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    image: backend_update-db
    container_name: db
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "20723:20723"
    restart: unless-stopped
