export { default as TrapoziedBgGrayLeft } from './trapoziedBgGrayLeft.svg'
export { default as TrapoziedBgGray1 } from './trapoziedBgGray1.svg'
export { default as TrapoziedBgGray2 } from './trapoziedBgGray2.svg'
export { default as TrapoziedBgGray3 } from './trapoziedBgGray3.svg'
export { default as TrapoziedBgGray4 } from './trapoziedBgGray4.svg'
export { default as TrapoziedBgGray5 } from './trapoziedBgGray5.svg'
export { default as LocationIcon } from './LocationIcon.svg'
export { default as ActivityIcon } from './ActivityIcon.svg'
export { default as LocationIconActive } from './LocationIconActive.svg'
export { default as ActivityIconActive } from './ActivityIconActive.svg'
export { default as SimilarityIcon } from './SimilarityIcon.svg'
export { default as SimilarityIconActive } from './SimilarityIconActive.svg'
export { default as TimelineIcon } from './TimelineIcon.svg'
export { default as TimelineIconActive } from './TimelineIconActive.svg'

export { default as BicycleIcon } from './obj_icons/Bicycle.svg'
export { default as CarIcon } from './obj_icons/car.svg'
export { default as CatIcon } from './obj_icons/cat.svg'
export { default as DogIcon } from './obj_icons/Dog Sit.svg'
export { default as PersonIcon } from './obj_icons/Person.svg'
export { default as BirdIcon } from './obj_icons/Bird.svg'
export { default as MobilePhoneIcon } from './obj_icons/Smartphone.svg'
export { default as LaptopIcon } from './obj_icons/Laptop.svg'
export { default as ComputerMonitorIcon } from './obj_icons/iMac.svg'
export { default as FoodIcon } from './obj_icons/Italian Pizza.svg'
export { default as TreeIcon } from './obj_icons/Oak Tree.svg'
export { default as ShirtIcon } from './obj_icons/T-Shirt.svg'
export { default as TrousersIcon } from './obj_icons/Trousers.svg'
export { default as TrafficLightIcon } from './obj_icons/Traffic Light.svg'

export { default as ObjectPosIcon } from './objectPosIcon.svg'
export { default as HistoryIcon } from './historyIcon.png'

export { default as jogging } from './Poses/jogging.png'
export { default as yoga } from './Poses/yoga.png'
export { default as halfBody } from './Poses/halfBody.png'
export { default as pushUp } from './Poses/pushUp.png'

export { default as BolbometoponMuricatum } from './MVK_LHE_images/Bolbometopon_Muricatum.jpg'
export { default as Chaetodontidae } from './MVK_LHE_images/Chaetodontidae.jpg'
export { default as CheilinusUndulatus } from './MVK_LHE_images/Cheilinus_Undulatus.jpeg'
export { default as CromileptesAltivelis } from './MVK_LHE_images/Cromileptes_Altivelis.png'
export { default as CrownOfThorns } from './MVK_LHE_images/Crown_of_Thorns_Starfish.jpg'
export { default as Fish } from './MVK_LHE_images/Fish.svg'
export { default as GiantClam } from './MVK_LHE_images/Giant_Clam.jpg'
export { default as Haemulidae } from './MVK_LHE_images/Haemulidae.jpeg'
export { default as Lobster } from './MVK_LHE_images/Lobster.png'
export { default as Lutjanidae } from './MVK_LHE_images/Lutjanidae.jpg'
export { default as Muraenidae } from './MVK_LHE_images/Muraenidae.jpg'
export { default as Ray } from './MVK_LHE_images/Ray.jpg'
export { default as Scaridae } from './MVK_LHE_images/Scaridae.jpg'
export { default as Shark } from './MVK_LHE_images/Shark.jpg'
export { default as Serranidae } from './MVK_LHE_images/Serranidae.jpg'
export { default as SeaCucumber } from './MVK_LHE_images/Sea_Cucumber.jpg'
export { default as Turtle } from './MVK_LHE_images/Turtle.jpg'
export { default as Urchin } from './MVK_LHE_images/Urchin.jpg'

export { default as Bipolar } from './MVK_LHE_images/Bipolar.jpg'
export { default as Clipper } from './MVK_LHE_images/Clipper.jpg'
export { default as Grasper } from './MVK_LHE_images/Grasper.jpg'
export { default as Hook } from './MVK_LHE_images/Hook.jpg'
export { default as Irrigator } from './MVK_LHE_images/Irrigator.jpg'
export { default as Scissors } from './MVK_LHE_images/Scissors.jpg'
export { default as SpecimenBag } from './MVK_LHE_images/Bag.jpg'
