export { default as TrapoziedBgGrayLeft } from './trapoziedBgGrayLeft.svg';
export { default as TrapoziedBgGray1 } from './trapoziedBgGray1.svg';
export { default as TrapoziedBgGray2 } from './trapoziedBgGray2.svg';
export { default as TrapoziedBgGray3 } from './trapoziedBgGray3.svg';
export { default as TrapoziedBgGray4 } from './trapoziedBgGray4.svg';
export { default as TrapoziedBgGray5 } from './trapoziedBgGray5.svg';
export { default as LocationIcon } from './LocationIcon.svg';
export { default as ActivityIcon } from './ActivityIcon.svg';
export { default as LocationIconActive } from './LocationIconActive.svg';
export { default as ActivityIconActive } from './ActivityIconActive.svg';
export { default as SimilarityIcon } from './SimilarityIcon.svg';
export { default as SimilarityIconActive } from './SimilarityIconActive.svg';
export { default as TimelineIcon} from './TimelineIcon.svg';
export { default as TimelineIconActive} from './TimelineIconActive.svg';