import json
import uuid
import os
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware

from agent.fusion import Fusion
from agent.graph import build_graph
from internal.postprocess import prepare_response
from tools.base import ToolExecutionContext
from tools.bootstrap import build_tool_manager

USE_STREAM = False

app = FastAPI()

# Add CORS middleware to allow websocket connections from frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, restrict this to your frontend domain
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

def mk_event(type_: str, session_id: str, payload: dict, message_id: str | None = None):
    return {
        "type": type_,
        "session_id": session_id,
        "message_id": message_id or str(uuid.uuid4()),
        "payload": payload,
    }

@app.on_event("startup")
async def startup():
    print("🚀 Starting LLM Agent Service...")
    try:
        tool_manager = build_tool_manager(milvus_client=None, es_client=None)
        app.state.graph = build_graph(tool_manager)
        app.state.tool_manager = tool_manager
        print("✅ Graph initialized successfully")
    except Exception as e:
        print(f"❌ Failed to initialize graph: {e}")
        raise


def _merged_score_of(item: Dict[str, Any]) -> float:
    try:
        return float(item.get("merged_score", 0.0) or 0.0)
    except Exception:
        return 0.0


def _id_of(item: Dict[str, Any]) -> int:
    try:
        return int(item.get("record_id", 0) or 0)
    except Exception:
        return 0


def _refine_call(call: Dict[str, Any], refinement: str, *, goal_query: str) -> Dict[str, Any]:
    """Heuristic call refinement (no external LLM calls).

    We keep tool/operation stable and adjust query/params to reflect user intent.
    """
    c = dict(call)
    r = (refinement or "").strip()
    if not r:
        return c

    base_query = (c.get("query") or goal_query or "").strip()
    low = r.lower()

    # Very small set of natural-language rewrites that tends to work across tools.
    if low.startswith("less "):
        # "less trees" -> "without trees" (more natural for semantic models)
        target = r[5:].strip()
        if target:
            c["query"] = f"{base_query} without {target}".strip()
        else:
            c["query"] = f"{base_query} ({r})".strip()
    elif low.startswith("no "):
        target = r[3:].strip()
        if target:
            c["query"] = f"{base_query} without {target}".strip()
        else:
            c["query"] = f"{base_query} ({r})".strip()
    elif low.startswith("without "):
        c["query"] = f"{base_query} {r}".strip()
    else:
        # generic refinement: append as a constraint/hint
        c["query"] = f"{base_query}. {r}".strip()

    return c


@dataclass
class AssistState:
    active_plan: Optional[Dict[str, Any]] = None
    fusion: Optional[Fusion] = None
    top_k_display: int = 10
    display_window_size: int = 3
    dataset: str = "lsc24"
    model: str = "default"

    applied_step_id: int = 0
    applied_merged_results: List[Dict[str, Any]] = None  # type: ignore[assignment]

    preview_step_id: Optional[int] = None
    preview_merged_results: Optional[List[Dict[str, Any]]] = None
    preview_items: Optional[List[Dict[str, Any]]] = None

    def __post_init__(self):
        if self.applied_merged_results is None:
            self.applied_merged_results = []


@app.websocket("/ws/agent")
async def ws_agent(ws: WebSocket):
    print(f"📥 New websocket connection request")
    await ws.accept()
    print(f"✅ Websocket connection accepted")
    await ws.send_text(json.dumps({"type": "assistant_message", "payload": {"text": "WS connected ✅"}}))
    print("📤 Sent initial connection message")

    # session id can be provided via query param, or generated by frontend
    session_id = ws.query_params.get("session_id") or f"sess-{uuid.uuid4()}"
    config = {"configurable": {"thread_id": session_id}}

    mode = (ws.query_params.get("mode") or "auto").strip().lower()
    if mode not in {"auto", "assist"}:
        mode = "auto"
    
    if not hasattr(app.state, "graph"):
        error_msg = "Graph not initialized"
        print(f"❌ {error_msg}")
        await ws.send_text(json.dumps(mk_event("error", session_id, {"message": error_msg})))
        await ws.close()
        return
    
    graph = app.state.graph
    tool_manager = getattr(app.state, "tool_manager", None)
    print(f"🔗 Session {session_id} connected")

    async def send_event(type_: str, payload: Dict[str, Any]):
        await ws.send_text(json.dumps(mk_event(type_, session_id, payload), ensure_ascii=False))

    # send hello/meta
    await send_event("meta", {"ok": True, "mode": mode})
    print(f"📤 Sent meta event to session {session_id}")

    assist = AssistState()
    # Optional override (keeps code defaults intact)
    try:
        assist.top_k_display = max(1, int(os.getenv("TOP_K_DISPLAY", str(assist.top_k_display))))
    except Exception:
        pass
    if mode == "assist":
        await send_event(
            "assistant_message",
            {"text": "Assist mode enabled (preview-first). I will run one step at a time and ask you to apply/discard."},
        )

    try:
        while True:
            raw = await ws.receive_text()
            msg = json.loads(raw)

            msg_type = msg.get("type")
            payload = msg.get("payload", {})

            # Assist-mode: handle step actions without going through the LangGraph router
            if mode == "assist" and msg_type == "assist_action":
                action = (payload.get("action") or "").strip()
                step_id = int(payload.get("step_id") or 0)
                refine_text = (payload.get("text") or "").strip()
                if not assist.active_plan:
                    await send_event("error", {"message": "No active plan. Send a query first."})
                    continue

                calls = assist.active_plan.get("calls") or []
                if step_id < 1 or step_id > len(calls):
                    await send_event("error", {"message": f"Invalid step_id={step_id}."})
                    continue

                expected = assist.applied_step_id + 1

                if action == "skip_step":
                    # Allow user to skip a proposed step without running preview.
                    if step_id != expected:
                        await send_event(
                            "error",
                            {"message": f"Can only skip next step ({expected}). Received step_id={step_id}."},
                        )
                        continue

                    # Mark it as advanced, but keep results unchanged.
                    assist.applied_step_id = step_id
                    assist.preview_step_id = None
                    assist.preview_merged_results = None
                    assist.preview_items = None

                    await send_event("assistant_message", {"text": f"Skipped step {step_id}."})
                    if step_id < len(calls):
                        await send_event("assist_step", {"step_id": step_id + 1, "call": calls[step_id]})
                    else:
                        await send_event("assistant_message", {"text": "All steps completed."})
                    continue

                if action == "refine_step":
                    # User can refine current proposed step as long as it is not applied.
                    # Allow refining the next step or an already-previewed (but not applied) step.
                    if step_id != expected and step_id != assist.preview_step_id:
                        await send_event(
                            "error",
                            {
                                "message": "Can only refine the currently proposed step (or the previewed-but-not-applied step).",
                            },
                        )
                        continue
                    if not refine_text:
                        await send_event("error", {"message": "Refinement text is empty."})
                        continue

                    goal_query = assist.active_plan.get("goal", "")
                    old_call = calls[step_id - 1]
                    new_call = _refine_call(old_call, refine_text, goal_query=goal_query)
                    calls[step_id - 1] = new_call
                    assist.active_plan["calls"] = calls

                    # Clear any preview because the call changed.
                    assist.preview_step_id = None
                    assist.preview_merged_results = None
                    assist.preview_items = None

                    await send_event(
                        "assistant_message",
                        {"text": f"Updated step {step_id} based on refinement: {refine_text}"},
                    )
                    await send_event("assist_step", {"step_id": step_id, "call": new_call})
                    continue

                if action == "run_step":
                    # enforce sequential for now
                    if step_id != expected:
                        await send_event(
                            "error",
                            {"message": f"Can only run next step ({expected}). Received step_id={step_id}."},
                        )
                        continue
                    if tool_manager is None:
                        await send_event("error", {"message": "Tool manager not initialized."})
                        continue

                    call = calls[step_id - 1]
                    tool_name = call["tool"]
                    op = call["operation"]
                    goal_query = assist.active_plan.get("goal", "")
                    query = call.get("query", goal_query)
                    params = call.get("params", {})

                    candidates = assist.applied_merged_results if op in ("rerank", "filter") else None
                    ctx = ToolExecutionContext(
                        operation=op,
                        query=query,
                        params=params,
                        candidates=candidates,
                        state={
                            "active_plan": assist.active_plan,
                            "plan_status": "assist_preview",
                            "messages": [],
                        },
                    )

                    await send_event("tool_start", {"tool": tool_name, "step_id": step_id, "operation": op})
                    res = await tool_manager.execute_tool(tool_name, ctx)
                    await send_event(
                        "tool_end",
                        {"tool": tool_name, "step_id": step_id, "operation": op, "ok": bool(res.success)},
                    )
                    if not res.success:
                        await send_event(
                            "error",
                            {"message": f"Step {step_id} failed: tool={tool_name} op={op} error={res.error}"},
                        )
                        await send_event(
                            "assist_step_result",
                            {
                                "step_id": step_id,
                                "ok": False,
                                "requires_apply": False,
                                "summary": f"Step {step_id} failed: {tool_name}.{op}",
                            },
                        )
                        continue

                    fusion_cfg = assist.active_plan.get("fusion", {"method": "rrf", "rrf_c": 60.0})
                    if assist.fusion is None:
                        assist.fusion = Fusion.from_plan_fusion(fusion_cfg)

                    prev_merged = assist.applied_merged_results
                    if op == "search":
                        print(f"First 5 in prev_merged: {prev_merged[:5]}")
                        print(f"First 5 in res.items: {res.items[:5]}")
                        preview_merged = assist.fusion.merge(prev_merged, res.items, params=params)
                        print(f"First 5 in preview_merged: {preview_merged[:5]}")
                    elif op == "rerank":
                        preview_merged = assist.fusion.merge(prev_merged, res.items, params=params)
                    elif op == "filter":
                        preview_merged = assist.fusion.filter(prev_merged, res.items, constraint=params.get("constraint", {}))
                    else:
                        await send_event("error", {"message": f"Unknown operation: {op}"})
                        continue

                    record_ids = [_id_of(r) for r in (preview_merged or [])[: assist.top_k_display]]
                    scores = [_merged_score_of(r) for r in (preview_merged or [])[: assist.top_k_display]]

                    preview_items: List[Dict[str, Any]] = []
                    if record_ids:
                        preview_items = await prepare_response(
                            dataset=assist.dataset,
                            model=assist.model,
                            record_ids=record_ids,
                            scores=scores,
                            display_window_size=assist.display_window_size,
                            top_k=assist.top_k_display,
                        )

                    assist.preview_step_id = step_id
                    assist.preview_merged_results = preview_merged
                    assist.preview_items = preview_items

                    await send_event("images_preview", {"items": preview_items, "step_id": step_id})
                    await send_event(
                        "assist_step_result",
                        {
                            "step_id": step_id,
                            "ok": True,
                            "requires_apply": True,
                            "summary": f"Preview ready for step {step_id}: {tool_name}.{op} ({len(preview_items)} items)",
                        },
                    )
                    continue

                if action == "apply_preview":
                    if assist.preview_step_id != step_id or assist.preview_items is None:
                        await send_event("error", {"message": "No matching preview to apply."})
                        continue
                    assist.applied_step_id = step_id
                    assist.applied_merged_results = assist.preview_merged_results or []
                    committed_items = assist.preview_items
                    assist.preview_step_id = None
                    assist.preview_merged_results = None
                    assist.preview_items = None

                    # Commit results to the grid (regular images event)
                    await send_event("images", {"items": committed_items, "step_id": step_id})

                    if step_id < len(calls):
                        next_call = calls[step_id]
                        await send_event(
                            "assist_step",
                            {"step_id": step_id + 1, "call": next_call},
                        )
                    else:
                        await send_event("assistant_message", {"text": "All steps completed."})
                    continue

                if action == "discard_preview":
                    if assist.preview_step_id != step_id:
                        await send_event("error", {"message": "No matching preview to discard."})
                        continue
                    assist.preview_step_id = None
                    assist.preview_merged_results = None
                    assist.preview_items = None
                    await send_event("assistant_message", {"text": f"Discarded preview for step {step_id}."})
                    # re-send current step prompt
                    call = calls[step_id - 1]
                    await send_event("assist_step", {"step_id": step_id, "call": call})
                    continue

                await send_event("error", {"message": f"Unknown assist_action '{action}'"})
                continue

            # 1) normalize client message -> text to feed graph
            if msg_type == "user_message":
                user_text = (payload.get("text") or "").strip()
            elif msg_type == "plan_decision":
                # keep existing backend contract: approve/reject are just user_texts
                user_text = (payload.get("decision") or "").strip()
            else:
                await send_event("error", {"message": f"Unknown type {msg_type}"})
                continue

            if not user_text:
                continue

            # 2) run graph and STREAM events
            # If your graph supports streaming events, use it.
            # If not, you can still do a single ainvoke() and then emit a few events.
            #
            # --- Preferred: streaming ---
            if USE_STREAM and hasattr(graph, "astream_events"):
                async for ev in graph.astream_events({"user_text": user_text}, config=config):
                    # IMPORTANT: you must map your ev -> UI event types.
                    # Below is a typical mapping pattern; adapt to your actual event schema.
                    #
                    # Example ev could be:
                    # {"kind":"routing", ...}, {"kind":"plan", ...}, {"kind":"tool_start", ...}, etc.

                    kind = ev.get("kind")

                    if kind == "routing_intent":
                        await ws.send_text(json.dumps(mk_event(
                            "routing_intent", session_id, ev["payload"]
                        )))

                    elif kind == "plan_draft":
                        await ws.send_text(json.dumps(mk_event(
                            "plan_draft", session_id, {"plan": ev["payload"]["plan"]}
                        )))

                    elif kind == "plan_status":
                        await ws.send_text(json.dumps(mk_event(
                            "plan_status", session_id, ev["payload"]
                        )))

                    elif kind == "tool_start":
                        await ws.send_text(json.dumps(mk_event(
                            "tool_start", session_id, ev["payload"]
                        )))

                    elif kind == "tool_end":
                        await ws.send_text(json.dumps(mk_event(
                            "tool_end", session_id, ev["payload"]
                        )))

                    elif kind == "images":
                        # send ONLY ids+scores; UI fetches thumbnails/details via imageService
                        await ws.send_text(json.dumps(mk_event(
                            "images", session_id, ev["payload"]
                        )))

                    elif kind == "assistant_token":
                        await ws.send_text(json.dumps(mk_event(
                            "assistant_token", session_id, {"text": ev["payload"]["text"]}
                        )))

                    elif kind == "assistant_message":
                        await ws.send_text(json.dumps(mk_event(
                            "assistant_message", session_id, {"text": ev["payload"]["text"]}
                        )))

            else:
                # --- Fallback: non-streaming ---
                out = await graph.ainvoke({"user_text": user_text}, config=config)
                print(out.keys())
                print("plan_status:", out.get("plan_status"))
                print("len(last_results):", len(out.get("last_results") or []))

                # 1) Always show the agent's text in chatbox (plan prompt / reply / status)
                reply = out.get("reply")
                if reply:
                    await send_event("assistant_message", {"text": reply})

                # 2) If there's a draft plan, send it to render approve/reject UI
                plan_status = out.get("plan_status")
                active_plan = out.get("active_plan")

                if plan_status == "draft" and active_plan:
                    await send_event("plan_draft", {"plan": active_plan})

                    if mode == "assist":
                        # Initialize assist state from the draft plan
                        assist.active_plan = active_plan
                        assist.applied_step_id = 0
                        assist.applied_merged_results = []
                        assist.preview_step_id = None
                        assist.preview_merged_results = None
                        assist.preview_items = None

                        calls = active_plan.get("calls") or []
                        assist.top_k_display = int(active_plan.get("top_k_display", 10))
                        assist.display_window_size = int(active_plan.get("display_window_size", 3))
                        first_call_params = (calls[0].get("params", {}) if calls else {})
                        assist.dataset = first_call_params.get("dataset", "lsc24")
                        assist.model = first_call_params.get("model", "default")
                        assist.fusion = None

                        if calls:
                            await send_event("assist_step", {"step_id": 1, "call": calls[0]})

                # 3) After approve, results appear in last_results
                last_results = out.get("last_results") or []

                # Results are now fully formatted with metadata from prepare_response
                # Just send them directly
                if last_results:
                    await send_event("images", {"items": last_results})
                    await send_event(
                        "assistant_message",
                        {"text": f"Sent {len(last_results)} results to the image grid."},
                    )


    except WebSocketDisconnect:
        print(f"🔌 Session {session_id} disconnected (client)")
        return
    except Exception as e:
        print(f"❌ Error in session {session_id}: {e}")
        import traceback
        traceback.print_exc()
        try:
            await ws.send_text(json.dumps(mk_event("error", session_id, {"message": str(e)})))
        except:
            pass
