# app.py
import json
import uuid
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware

from agent.graph import build_graph
from tools.bootstrap import build_tool_manager

USE_STREAM = False

app = FastAPI()

# Add CORS middleware to allow websocket connections from frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, restrict this to your frontend domain
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

def mk_event(type_: str, session_id: str, payload: dict, message_id: str | None = None):
    return {
        "type": type_,
        "session_id": session_id,
        "message_id": message_id or str(uuid.uuid4()),
        "payload": payload,
    }

@app.on_event("startup")
async def startup():
    print("🚀 Starting LLM Agent Service...")
    try:
        tool_manager = build_tool_manager(milvus_client=None, es_client=None)
        app.state.graph = build_graph(tool_manager)
        print("✅ Graph initialized successfully")
    except Exception as e:
        print(f"❌ Failed to initialize graph: {e}")
        raise

def evt(type_: str, payload: dict):
    return json.dumps({"type": type_, "payload": payload}, ensure_ascii=False)

@app.websocket("/ws/agent")
async def ws_agent(ws: WebSocket):
    print(f"📥 New websocket connection request")
    await ws.accept()
    print(f"✅ Websocket connection accepted")
    await ws.send_text(json.dumps({"type": "assistant_message", "payload": {"text": "WS connected ✅"}}))
    print("📤 Sent initial connection message")

    # session id can be provided via query param, or generated by frontend
    session_id = ws.query_params.get("session_id") or f"sess-{uuid.uuid4()}"
    config = {"configurable": {"thread_id": session_id}}
    
    if not hasattr(app.state, "graph"):
        error_msg = "Graph not initialized"
        print(f"❌ {error_msg}")
        await ws.send_text(json.dumps(mk_event("error", session_id, {"message": error_msg})))
        await ws.close()
        return
    
    graph = app.state.graph
    print(f"🔗 Session {session_id} connected")

    # send hello/meta
    await ws.send_text(json.dumps(mk_event("meta", session_id, {"ok": True})))
    print(f"📤 Sent meta event to session {session_id}")

    try:
        while True:
            raw = await ws.receive_text()
            msg = json.loads(raw)
            text = msg.get("payload", {}).get("text", "")

            # Echo back in the exact format the UI expects
            await ws.send_text(json.dumps({
                "type": "assistant_message",
                "payload": {"text": f"you said: {text}"}
            }))

            msg_type = msg.get("type")
            payload = msg.get("payload", {})

            # 1) normalize client message -> text to feed graph
            if msg_type == "user_message":
                user_text = payload.get("text", "").strip()
            elif msg_type == "plan_decision":
                # keep your current backend contract:
                # "approve"/"reject" are just user_texts
                user_text = payload.get("decision", "").strip()
            else:
                await ws.send_text(json.dumps(mk_event("error", session_id, {"message": f"Unknown type {msg_type}"})))
                continue

            if not user_text:
                continue

            # 2) run graph and STREAM events
            # If your graph supports streaming events, use it.
            # If not, you can still do a single ainvoke() and then emit a few events.
            #
            # --- Preferred: streaming ---
            if USE_STREAM and hasattr(graph, "astream_events"):
                async for ev in graph.astream_events({"user_text": user_text}, config=config):
                    # IMPORTANT: you must map your ev -> UI event types.
                    # Below is a typical mapping pattern; adapt to your actual event schema.
                    #
                    # Example ev could be:
                    # {"kind":"routing", ...}, {"kind":"plan", ...}, {"kind":"tool_start", ...}, etc.

                    kind = ev.get("kind")

                    if kind == "routing_intent":
                        await ws.send_text(json.dumps(mk_event(
                            "routing_intent", session_id, ev["payload"]
                        )))

                    elif kind == "plan_draft":
                        await ws.send_text(json.dumps(mk_event(
                            "plan_draft", session_id, {"plan": ev["payload"]["plan"]}
                        )))

                    elif kind == "plan_status":
                        await ws.send_text(json.dumps(mk_event(
                            "plan_status", session_id, ev["payload"]
                        )))

                    elif kind == "tool_start":
                        await ws.send_text(json.dumps(mk_event(
                            "tool_start", session_id, ev["payload"]
                        )))

                    elif kind == "tool_end":
                        await ws.send_text(json.dumps(mk_event(
                            "tool_end", session_id, ev["payload"]
                        )))

                    elif kind == "images":
                        # send ONLY ids+scores; UI fetches thumbnails/details via imageService
                        await ws.send_text(json.dumps(mk_event(
                            "images", session_id, ev["payload"]
                        )))

                    elif kind == "assistant_token":
                        await ws.send_text(json.dumps(mk_event(
                            "assistant_token", session_id, {"text": ev["payload"]["text"]}
                        )))

                    elif kind == "assistant_message":
                        await ws.send_text(json.dumps(mk_event(
                            "assistant_message", session_id, {"text": ev["payload"]["text"]}
                        )))

            else:
                # --- Fallback: non-streaming ---
                out = await graph.ainvoke({"user_text": user_text}, config=config)
                print(out.keys())
                print("plan_status:", out.get("plan_status"))
                print("len(last_results):", len(out.get("last_results") or []))

                # 1) Always show the agent's text in chatbox (plan prompt / reply / status)
                reply = out.get("reply")
                if reply:
                    await ws.send_text(evt("assistant_message", {"text": reply}))

                # 2) If there's a draft plan, send it to render approve/reject UI
                plan_status = out.get("plan_status")
                active_plan = out.get("active_plan")

                if plan_status == "draft" and active_plan:
                    await ws.send_text(evt("plan_draft", {"plan": active_plan}))

                # 3) After approve, results appear in last_results
                last_results = out.get("last_results") or []

                # Results are now fully formatted with metadata from prepare_response
                # Just send them directly
                if last_results:
                    await ws.send_text(evt("images", {"items": last_results}))
                    await ws.send_text(evt("assistant_message", {"text": f"Sent {len(last_results)} results to the image grid."}))


    except WebSocketDisconnect:
        print(f"🔌 Session {session_id} disconnected (client)")
        return
    except Exception as e:
        print(f"❌ Error in session {session_id}: {e}")
        import traceback
        traceback.print_exc()
        try:
            await ws.send_text(json.dumps(mk_event("error", session_id, {"message": str(e)})))
        except:
            pass
