# Use a lightweight Python base image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy dependency list first for better caching
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the FastAPI app source code
COPY . /app

# Expose app port (change if needed)
EXPOSE 20735

# Run the FastAPI app using uvicorn
COPY khang.sh .
RUN chmod +x khang.sh
CMD ["bash", "khang.sh"]
